title: HKUST ESG reading group
description: HKUST ESG reading group
author: HKUST ESG reading group
github: https://github.com/HKUST-ESG
about: HKUST ESG reading group

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://hkust-esg.github.io"

urls:
    - text: Papers
      url: /papers
    - text: By Category
      url: /category/all

url: "https://hkust-esg.github.io"
baseurl: ""
paginate: 50
per_page: 50
paginate_path: "papers/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
